### ISSUE TITLE
Not properly displaying a site 

### ISSUE THREAD

**Issue by Den4will** [IP-CAM/Opencart-v.1.5.6.5-LIGHT-Install-PHP-v.7.4.23#5]
Hello. Not properly displaying a site after installation. 
![Screenshot_2021-09-06-02-23-31-816_com opera mini native~2](https://user-images.githubusercontent.com/89627463/132144523-d5f3240f-180a-43e4-bd39-1e0a050e4a7f.jpg)

Some attention downside - "You are on a DEMO Shop Site. No orders will be processed!"

**Comment by condor2** [comment]
You have made this changes after install?
https://github.com/IP-CAM/Opencart-v.1.5.6.5-LIGHT-Install-PHP-v.7.4.22/blob/master/upload/IMPORTANT_see_image-FIRST.png

**Comment by Den4will** [comment]
> You have made this changes after install?
> https://github.com/IP-CAM/Opencart-v.1.5.6.5-LIGHT-Install-PHP-v.7.4.22/blob/master/upload/IMPORTANT_see_image-FIRST.png

My Opencart installation in main folder. 

/russia.beget.tech/public_html/catalog

Or I must use  /public_html/  correct?
This requirements before to start installation?

**Comment by condor2** [comment]
You need to edit all files from that images and change openshop.li with your store URL.

**Comment by Den4will** [comment]
Displaying site is normal right now. But installation and uninstallation modules not working so far. **Only after cleaning cash of system result coming.**
